
name: SAST

on:
  workflow_call:
    inputs:
      APP_TYPE:
        type: string
        required: true
      APP_NAME:
        type: string
        required: true
      APP_PATH:
        type: string
        required: true
    secrets:
      SHIFTLEFT_ACCESS_TOKEN:
        required: true

jobs:
  qwiet-sast-analysis:
    runs-on: ubuntu-20.04
    steps:
    - name: "☁️ Checkout repository"
      uses: actions/checkout@v3
  
    - name: Download the Qwiet CLI and set permissions
      run: |
        curl https://cdn.shiftleft.io/download/sl > qwiet && chmod a+rx qwiet

      # Qwiet requires >= Java 1.8
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
        
    - name: AnalyzeJava Application with Qwiet
      working-directory: ${{ inputs.APP_PATH }}
      if: inputs.APP_TYPE == 'java'
      run: |
        mvn clean install
        ${{ github.workspace }}/qwiet analyze --java --app ${{ inputs.APP_NAME }} --tag branch=${{ github.head_ref }} --vcs-prefix-correction "*=/src/main/java" --wait ./${{ inputs.APP_NAME }}/target/${{ inputs.APP_NAME }}.jar
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}

    - name: Analyze JS with Qwiet
      working-directory: ${{ inputs.APP_PATH }}
      if: inputs.APP_TYPE == 'js'
      run: ${{ github.workspace }}/qwiet analyze --app ${{ inputs.APP_NAME }} --tag branch=${{ github.head_ref }} --js .
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        
    - name: Report export process
      run: ${{ github.workspace }}/qwiet check-analysis --branch=${{ github.head_ref }} --app ${{ inputs.APP_NAME }} --report ${{ inputs.APP_PATH }}report.json
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}

    - name: Upload ShiftLeft SAST report
      uses: actions/upload-artifact@v2
      with:
        name: shiftleft-report
        path: ${{ inputs.APP_PATH }}report.json
