name: Angular Frontend CI   

on:
  push:
    branches:
      - master
    paths:
      - "app/src/main/**"
      - ".github/workflows/**"
      - "*"

jobs:
  sast-scan:
    uses: kryptos-vigneshr/docker-nginx-hello-world/.github/workflows/qwiet.yaml@master
    with:
      APP_TYPE: js
      APP_PATH: app/
      APP_NAME: test
    secrets:
      SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
