name: Parent Workflow

on:
  workflow_run:
    workflows: ["Trivy Image Scanning"]
    types:
      - completed

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Child Workflow
        uses: ./.github/workflows/main.yml
        with:
          input_parameter: "example value"
