name: CI

on:
  push:
    branches:
      - master 
      
  workflow_run:
    workflows: main
jobs:
  app-setup:
    uses: favedom-dev/github-reusable-workflow/.github/workflows/app-setup.yaml@master
    with:
      OVERRIDE_NAME: pw-dims

  repo-version:
    uses: favedom-dev/github-reusable-workflow/.github/workflows/repo-version.yaml@master
    with:
      MONOREPO_APP: ${{ needs.app-setup.outputs.NAME }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
  sast-scan:
    uses: robinjeya/docker-nginx-hello-world/.github/workflows/main.yml@master
    with:
      NAME: ${{ app-setup.outputs.NAME }}
      VERSION: ${{ repo-version.outputs.version }}
 
