name: CI

on:
  push:
    branches:
      - master 
      
  workflow_call:
  
jobs:
  app-setup:
    uses: favedom-dev/github-reusable-workflow/.github/workflows/app-setup.yaml@master
    with:
      OVERRIDE_NAME: pw-dims
 
  repo-version:
    uses: favedom-dev/github-reusable-workflow/.github/workflows/repo-version.yaml@master
    with:
      MONOREPO_APP: ${{ needs.app-setup.outputs.NAME }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
  sast-scan:
    runs-on: ubuntu-20.04
    steps:
    - uses: ./.github/workflows/main.yml@ci
      with:
       NAME: ${{ needs.app-setup.outputs.NAME }}
       VERSION: ${{ needs.repo-version.outputs.version }}

 
